### ISSUE TITLE
aqm_lbcs job failed on Cactus and Dogwood because of loading module w3nco/2.4.1

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM-utils#13]
The job failed on both Cactus and Dogwood. It complains the 

++ bash[71]: /usr/share/lmod/lmod/libexec/lmod bash load aqm_lbcs.local
Lmod has detected the following error: These module(s) or extension(s) existo
**but cannot be loaded as requested: "w3nco/2.4.1"**
   Try: "module spider w3nco/2.4.1" to see how to load the module(s).

============
However, the module was loaded successfully manually on Dogwood. 

@chan-hoo

**Comment by HaixiaLiu-NOAA** [comment]
@chan-hoo Could you please look into this issue? Thanks.

**Comment by JianpingHuang-NOAA** [comment]
I moved the following line 

load(pathJoin("w3nco", os.getenv("w3nco_ver")))

to the bottom of the aqm_lbcs.local.lua file. It works now.  @chan-hoo @HaixiaLiu-NOAA
