### ISSUE TITLE
gefs2clbcs failed when the code was compiled with debug flags of "-ftrapuv -check all"

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM-utils#17]
gefs2clbcs failed when the code was compiled with debug flags of "-ftrapuv -check all".   This is part of IT tests required by NCO to support AQMv7 implementation.

The CMakeLists.txt is available on Cactus at 

/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88i/sorc/AQM-utils

Below is error message, 

 FAST_BYTESWAP ALGORITHM HAS BEEN USED AND DATA ALIGNMENT IS CORRECT FOR          4  )
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source
gefs2lbc_para      00000000004E6C5B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014F6305968C0  Unknown               Unknown  Unknown
gefs2lbc_para      000000000044B467  Unknown               Unknown  Unknown
gefs2lbc_para      000000000040BB52  Unknown               Unknown  Unknown
[libc-2.31.so](http://libc-2.31.so/)       000014F63027524D  __libc_start_main     Unknown  Unknown
gefs2lbc_para      000000000040BA6A  Unknown               Unknown  Unknown
[nid001086.cactus.wcoss2.ncep.noaa.gov](http://nid001086.cactus.wcoss2.ncep.noaa.gov/): rank 1 died from signal 6 and dumped core
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
gefs2lbc_para      00000000004E6C5B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014AD51E7B8C0  Unknown               Unknown  Unknown
gefs2lbc_para      00000000005851EA  Unknown               Unknown  Unknown
gefs2lbc_para      0000000000539651  Unknown               Unknown  Unknown
gefs2lbc_para      0000000000449445  Unknown               Unknown  Unknown
gefs2lbc_para      000000000040BB52  Unknown               Unknown  Unknown
[libc-2.31.so](http://libc-2.31.so/)       000014AD51B5A24D  __libc_start_main     Unknown  Unknown
gefs2lbc_para      000000000040BA6A  Unknown               Unknown  Unknown
Application 1c511ef2-628e-4961-a083-528997f48a3e resources: utime=37s stime=3s maxrss=1595632KB inblock=7067908 oublock=24 minflt=36965 majflt=26 nvcsw=2253 nivcsw=81

**Comment by ytangnoaa** [comment]
The GEFS's top pressure sometimes reaches zero, and causes the divide-by-zero issue.
 This PR sets the minimum pressure to avoid it. 

https://github.com/NOAA-EMC/AQM-utils/pull/16

**Comment by BrianCurtis-NOAA** [comment]
Is #16 was merged, this can be closed.
