### ISSUE TITLE
GEFS2LBC_PARA: GNU Build Error due to Divide by Zero 

### ISSUE THREAD

**Issue by drnimbusrain** [NOAA-EMC/AQM-utils#6]
When building UFS-SRW-App [develop] ATMAQ on other machines that use GNU Fortran compiler (e.g., GMU Hopper), there is issue with compiling gefs2clbcs_para because of a purposeful divide by zero in the code.  This should be revised to satisfy building UFS-SRW-App using different compilers.

/sorc/AQM-utils/sorc/gefs2clbcs_para.fd/gefs2lbc_para.f90:588:15:

  588 |      fillval=0./0.
      |               1
Error: Division by zero at (1)

@ytangnoaa

**Comment by ytangnoaa** [comment]
The pull request is created for this issue of GNU compiler 

https://github.com/NOAA-EMC/AQM-utils/pull/7

**Comment by chan-hoo** [comment]
@drnimbusrain, The PR #7 has been merged. Can you check ([b066931](https://github.com/NOAA-EMC/AQM-utils/commit/b066931582e528e8a8f972c35776828afbd200cf)) again if it works on GNU. If so, I'll update the hash number in the UFS SRW App.

**Comment by drnimbusrain** [comment]
@chan-hoo @ytangnoaa   OK, I have checked that change, and it fixes the error.  Thank you!

**Comment by drnimbusrain** [comment]
@chan-hoo Have you updated the has in the UFS-SRW-App for this yet?

**Comment by chan-hoo** [comment]
I've updated it on the 'online-cmaq' branch.
The change to the 'develop' branch is under review now (https://github.com/ufs-community/ufs-srweather-app/pull/664).

**Comment by drnimbusrain** [comment]
Thanks Chan-Hoo!
